baseURL: "https://dejongsoftwareengineering.nl"
languageCode: "en-us"
title: "Recipes loved by our family"
theme: "gochowdown"
author:
name: Edwin de Jong
copyright: Edwin de Jong
enableRobotsTXT: true
googleAnalytics: G-G20FB7TKMF
GoogleAnalytics: G-G20FB7TKMF

params:
  author: Edwin de Jong
  description: Recipes loved by our family
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent:
  hidecredits: false
  hidecopyright: false
  showNavTitle: false            # Boolean: show site title in nav bar
  custom_css:
    - style.css
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Category
      weight: 2
      url: /category/
    - name: Cuisine
      weight: 3
      url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags

